### PR TITLE
Explain that we require the development version of Lean, close #37

### LINKED ISSUE #37: Compilation issues in meta_data.lean
I'm using `Lean (version 3.2.0, commit 9a386ae188e8, Release)`. When I try to compile meta_data.lean with `lean --make meta_data.lean` I'm getting the following error:

```
error: unknown attribute [user_command]
error: unknown identifier 'decl_meta_info'
warning: declaration 'unfinished_cmd' uses sorry
```

I can get rid of by commenting out this piece of code from meta_data.lean

```
135 --@[user_command]
136 --meta def unfinished_cmd (meta_info : decl_meta_info) (_ : parse $ tk "unfinished") : lean.parser unit :=
137 --do nm ← ident,
138 --   tk ":",
139 --   tp ← lean.parser.pexpr 0,
140 --   tk ":=",
141 --   struct ← lean.parser.pexpr,
142 --   add_unfinished nm tp struct
```

I'd go ahead and do it, but I don't understand this sort of metaprogramming in lean (and what's being achieved with this piece of code), so I'd like a second opinion here.

This is a blocker of #36, as compilation of every module depends on meta_data, which doesn't compile as of yet.

### PR DESCRIPTION
**Pull request by andrejbauer**
This closes #37 by explaining that for now contributors have to compile the latest and greatest Lean.

### CODE REVIEW

**Comment by picrin** [comment]
Is that desirable though? I can see 2 downsides:

1) requiring our users/contributors to compile lean themselves makes it harder to contribute
2) it makes our CI more complicated and therefore brittle and fragile.

Instead, if we agree to limit ourselves to the newest **released** version of lean, we avoid both of these downsides. And there isn't even so much depending on these unreleased features at the moment.

**Comment by andrejbauer** [comment]
I don't know if it's desirable, but it is a fact of life that the current version uses features not present in Lean 3.2.0. It's not like we have a huge user base. We are experimenting, and it's ok to experiment with features that will appear in the next version of Lean in a couple of months. Perhaps people closer to Lean can tell us when that might be.

You're planning as if there's a product and a user base that we need to worry about. We have neither.

**Comment by andrejbauer** [comment]
As per your reasons:

1. We do not have any users.
2. Tough luck.

**Comment by picrin** [comment]
I'm aware of one place we're using [unreleased features](https://github.com/formalabstracts/formalabstracts/blob/master/meta_data.lean#L135), and it looks like we could do without it. Are there any other places, where unreleased features are absolutely required?

1. With this type of project we hope to have more and more contributors as we grow. Making it easy to contribute is an important feature of this project.
2. I still think that having simple CI which always works would be desirable, but could be convinced otherwise if we really need those unreleased features.

**Comment by andrejbauer** [comment]
As for this PR, it does *not* introduce experimental features of Lean. It *only* explains to users that this has happened. So, I don't think it makes sense to block an explanation of the current state of affairs because you do not like the current state of affairs. It would probably be better to accept this PR so that people are at least not surprised, and then open a separate issue in which we discuss using experimental features.

**Comment by andrejbauer** [comment]
We really need those features, as they implement `unfinished`, and you can't just get rid of that. That's an important part of what we're trying to do. In any case, this discussion should continue in a separate issue.

**Comment by andrejbauer** [comment]
Now that we have #40, I hope we can accept this PR, as it just records the actual state of affairs in the documentation. It doesn't actually add anything controversial to the repo.

**Pull request merged**
