### PR TITLE
Adding FAbstract for Fermat Last Theorem.

### PR DESCRIPTION
**Pull request by picrin**
Fermat Last theorem is a good example of a test FAbstract, as
it is very small and allows us to figure out

1. How do we give references to the original paper
2. How do we present the FAbstract (lean source code, lean book, markdown, etc.)
3. How do we accept a public contribution (1 or 2 reviewers, pull requests, etc.)
4. Coding Standards
5. Continuous integration

### CODE REVIEW

**Comment by JamesHDavenport** [comment]
I think "the original paper" makes little sense here: we should use a major textbook.

**Comment by andrejbauer** [comment]
If we are formalizing snippets of mathematical knowledge, then we should allow many references for one snippet. But I thought this is about formalizing the content of mathematical texts (papers, textbooks), in which case there will obviously be a primary reference, and possibly a list of secondary references.

**Comment by DavidMichaelRoberts** [comment]
The paper you cite is in fact by *only* Wiles. And the literal statement therein of FLT is:

u,v,w: Q, p:Prime |- u^p + v^p + w^p = 0 -> uvw=0.

(assuming of course Fermat's contribution for n=4, this is enough for all n > 2). I don't know how specific you want to be for the fabstract...

**Comment by picrin** [comment]
Cheers, would you like to raise a merge request to correct these?

**Comment by DavidMichaelRoberts** [comment]
I'm not sure how. Fork, edit, then request?

And, I forgot to include p≥3 in the statement. 2 is also prime! :-/

**Comment by picrin** [comment]
Yes, fork edit and pull request will work. Good point!

**Comment by robertylewis** [comment]
I wouldn't worry about it for now, unless you want to change it just for fun. This repository is sort of on hold at the moment.

**Pull request merged**
