### PR TITLE
P = NP

### PR DESCRIPTION
**Pull request by digama0**
I have attached this one to S. Cook's paper, which is generally credited with first conjecturing this Clay Millenium problem, but a proper fabstract for this paper should also formalize the proven results of the paper (reduction to SAT).

### CODE REVIEW

**Comment by andrejbauer** [comment]
It doesn't have to formalize the proof, just state that the proof is there!

**Comment by andrejbauer** [comment]
I disagree with the renaming of `.markdown` files to `.md`. In any case, if you are going to propose such a change, it's better to make two PRs, one with the change and the other with the content of the new fabstract. Could you please make a PR with does *just* the fabstract? (And open an issue if you think we need to talk about `.markdown` vs `.md`.) Thanks for contributing!

**Comment by digama0** [comment]
Those were supposed to be separate PRs, but somehow the other tagged along for the ride. Now this PR is just the P=NP part.

**Comment by andrejbauer** [comment]
Thank you for your PR, I think it poses a couple of very interesting questions about fabstracts.

1. One of the reviewers (namely I) disagrees with the formalization of part of the fabstract. How do we proceed?
2. How much do we want to enforce various styling conventions (such as use of infix operators that is not really essential, and is just obfuscation in the opinion of a reviewer).

More generally, we're quickly hitting upon the question on **how to curate fabstract**, and we have not even gotten started.

My belief is that there are three ideals:

* The cost of writing a fabstract must be low.
* Fabstracts must be a distributed system as much as possible (no monolithic structure anywhere).
* Fabstracts must be correct.

One possibility would be as follows: when correctness doubts arise, the arbiter should be published literature. So please point to literature which defines Turing machines the way you did. When it turns out that different pieces of literature differ in definitions of concepts, we will simply have several versions of a single concept, but at least we will know where those came from (because they will point back to literature).

**Comment by andrejbauer** [comment]
Another possibility is to appoint official editors who have the last word. In this case `fabstracts` would be less like a hippy commune and more like a journal. I think we need to bring in Thomas Hales, and others, to see what their opinions are.

**Comment by digama0** [comment]
> One of the reviewers (namely I) disagrees with the formalization of part of the fabstract. How do we proceed?

Your sentence is slightly ambiguous. Do you mean that you disagree that there are theorems in this fabstract (i.e. it is partly formalized), or do you disagree that only part of the source paper has been formalized (stated)?

In the second case, I agree with you, and there are a few ways to proceed. I originally wanted to formalize a "folklore" conjecture, namely P = NP, but the fabstracts format forces me to associate this with a particular paper. This causes "scope creep" of a sort, because now I must state all the theorems in the paper, in addition to the result I started with. For now, we can treat this as future work (to formalize SAT and polynomial time reduction etc.).

In the first case, I strongly disagree. It is entirely backward to view a fabstract negatively if the author took it upon themselves to already get started on some part of formalizing the result. I think curation should be ambivalent about the level of formalization of proofs done by the author - it causes no harm, and is what we are indirectly hoping for in the end anyway.

> How much do we want to enforce various styling conventions (such as use of infix operators that is not really essential, and is just obfuscation in the opinion of a reviewer).

Although I don't feel strongly about this, I think that fabstracts should not curate formalization style much if at all, to maximize inclusivity.

> * The cost of writing a fabstract must be low.
> * Fabstracts must be a distributed system as much as possible (no monolithic structure anywhere).
> * Fabstracts must be correct.

The second point lines up best with my argument on low curation. In any case if this project takes off the maintenance burden will be harsh on the curators if the style guides are extensive.

What do you mean by "correct"? Of course the fabstracts will be *formally* correct, that's the whole point of using Lean. But I think you mean something else - correctness to the source material. This is a trickier thing, and I rather think that we should allow some leeway with the formalizer to choose definitions that differ from the source paper.

I think this will be a controversial point of view, but as was pointed out at the meeting there is an art to choosing definitions correctly, and the formalizer is not simply playing the role of a secretary here - they are making decisions on how to best formalize a concept or topic within the given framework, and sometimes that means diverging from the source material.

But let's say you still think that I have poorly chosen my definition, or you don't think these are really Turing machines, but I the formalizer think that my chosen definition is the easiest to work with, and would rather not compromise on it. In a standard formal proof setting, my response would be to prove that my notion of turing machines is equivalent to yours or some chosen literature reference, but this may involve a nontrivial proof obligation, which we are trying to avoid. What should be done in this case? Put another way, how do we respond to formalizers with "original work"?

**Comment by andrejbauer** [comment]
Suppose I believe that your formalization is mathematically incorrect. Then what? That was my question. We can practice, here:

In your definition of a Turing machine, how do we get the set of instructions? You defined a machine to be a transition function, but it is *essential* to computability theory that Turing machines have finite programs (the quadruples). How do you propose to write down the Gödel code of a Turing machine? It's just a wrong definition. So I cannot agree with the PR.

**Comment by andrejbauer** [comment]
We should look to Wikipedia and learn from it (although perhaps not the bashing of experts by Wikipedia admins). On Wikipedia it is better to accept a broken page than to have no page at all, since it can be improved later.

For instance, if you are not going to list all the results in the Cook paper, you should not be forced to. But I think you *should* indicate formally that there are some other results. There are several levels of this:

1. Postulate a constant `other_results` of type `Type` and include it among the results.
2. For each result that you are not going to formalize, introduce a type `result_X_Y : Type`, and an constant `proof_of_X_Y` and then include the proof as one of the results. This way it's clear that the result is there but you did not formalize it. Others can then pick up on it.

**Comment by digama0** [comment]
The set of states and alphabet of a turing machine are given as inputs to the definition `turing_machine`. This definition as given allows infinite sets to be input, and should not be construed as necessarily making any sense in that domain. But it is easier to work with such a definition since it allows for substituting arbitrary inductive types for the alphabet rather than playing with indices. The restriction to a particular finite set and a particular finite alphabet is done in the definition `TATM` and `NTATM`, and it is these that are used in the definitions `P` and `NP` in the conjecture.

One could add additional constraints to the sets saying that they are finite, but a theory of finite sets is forthcoming in Lean 3 and it is inessential to stating this conjecture.

**Comment by andrejbauer** [comment]
Where is the *instruction set*?

**Comment by digama0** [comment]
Maybe I don't know what you mean by that term. https://en.wikipedia.org/wiki/Turing_machine doesn't use that term to refer to any part of the Turing machine. There is a finite partial function, that's the transition function that makes up the only piece of explicit data in the Turing machine under my representation, and since it's a Turing machine that can only go left and right and write symbols on the tape the "instruction set" is I suppose the inductive type `direction`, which only has two values since at each step the turing machine writes a symbol and moves either left or right.

**Comment by digama0** [comment]
Actually, on second thought I think that even trying to maintain correctness with curation is a bad idea. I think we should accept all comers, as long as they verify, match whatever style guides exist and are not obviously off topic. The process of getting the formalization right can be done on an ongoing basis, with future PRs fixing earlier ones when issues are discovered. Importantly, this means that possibly incorrect fabstracts are amended with a counter-proposal rather than simply being rejected in review. I don't have any trouble with the level of scrutiny you are giving this PR, but I don't think it scales well.

**Comment by andrejbauer** [comment]
I think what I am saying is that your transition function needs to map to `bool` (the one for nondeterministic machines, the deterministic ones are fine). A Turing machine is a finite discrete object, but a map into `Prop` is not. It may or may not be the case in Lean that `Prop` and `bool` are the same thing, but I would not rely on that.

Regarding curration of correctness. I think I agree with you that this would be impossible to do. The only hope we have is to set up things so that contributors clean up after other contributors.

And another point: I think there should be no `folklore`. One may refer to something in another fabstract, but maintaining folklore will be impossible. For instance, you and I might disagree about the folklore definition of Turing machines, and then what? One of us will go away sulking and will put his own definition in a fabstract. At that point we might as well abolish folklore.

I have one last remaining doubt. If someone thinks that something is wrong in a fabstract, do they get a chance to say so *in the source code*? Clearly, they can open an issue or a PR, but that's not the same thing. Perhaps it's enough to open a PR which inserts a comment explaining what the problem is. Wikipedia has "talk" pages for this purpose, what have we got?

Having said all this, I think it's time to accept your PR, but I am stating for the record that I think your definition of Turing machines is wrong because they map into `Prop` rather than `bool`.

**Comment by robertylewis** [comment]
> Fabstracts must be correct.

Not only is it hard to check fabstracts for correctness, it can be hard to even say what it means for an fabstract to be correct. 

After all, we're translating informal mathematics (nominally based on ZFC, for the most part) to a particular type theory. One definition of correct could be: under an interpretation of Lean into ZFC, the theorem statement in Lean maps to the ZFC formalization of the original informal statement. I don't think this is what we want, and if I understood our conversation correctly, @favonia says it is theoretically impossible to achieve. 

So we're aiming for an "informal" translation of informal math to type theory. In particular, statements of theorems with a foundational flavor to them (category theory, set theory, maybe computability theory?) may be more approximate than we might hope. I think what we can aim for is to get interfaces correct. The foundations of Lean may force a certain definition of a Turing machine to be more or less similar to the traditional, informal definition. We shouldn't try to write down the definition that gets us closest. Instead, we should look for an interface that any definition of a Turing machine should meet, and maybe we can agree on what that interface is. Many fabstracts will be agnostic about the implementation of this interface, and those that aren't (say, results comparing different implementations) can and should include formalizations of the implementations, as the details are a crucial part of those results.

I think I'm basically saying that the project should be as foundation-independent as possible. Despite being written in Lean, these abstracts are not fully formal and are not specifying something 100% precise. We still achieve the goals of the project (curating theorem statements, interrelations between abstracts, introducing mathematicians to formalization). Instead of having lots of definitions in the folklore folder, we should have mostly axiomatized specifications. There will still be disagreement about the specifications sometimes, but hopefully less than with full definitions, and results whose statements depend on minutiae of the spec will probably want to include an implementation anyway.

**Comment by fpvandoorn** [comment]
Two remarks here:

* I think we should generally accept definitions which are only classically correct. I don't think mathematicians will be interested in thinking how their definition is constructively correct.

* I think we should have `folklore`.  If my paper depends on category theory, I don't want to search for `fabstacts/Bauer_A_InjBaireNat/categories.lean`.

**Comment by robertylewis** [comment]
> I have one last remaining doubt. If someone thinks that something is wrong in a fabstract, do they get a chance to say so in the source code? Clearly, they can open an issue or a PR, but that's not the same thing. Perhaps it's enough to open a PR which inserts a comment explaining what the problem is. Wikipedia has "talk" pages for this purpose, what have we got?

I think using issues or PRs is reasonable here. Give the author of the fabstract a chance to respond; if they don't, and the community and/or curators agree that something is incorrect, then they are free to change it.

We have to assume people will submit fabstracts and disappear, they're not all going to stick around to maintain them. If we can manage to put together and keep a competent curator team, the Mizar MML model will probably be the most successful here.

**Comment by favonia** [comment]
> After all, we're translating informal mathematics (nominally based on ZFC, for the most part) to a particular type theory. One definition of correct could be: under an interpretation of Lean into ZFC, the theorem statement in Lean maps to the ZFC formalization of the original informal statement. I don't think this is what we want, and if I understood our conversation correctly, @favonia says it is theoretically impossible to achieve.

Hi, I believe a large part of mathematical statements can be precisely recovered by looking for their preimages in some ZFC interpretation of the type theory Lean is using. Before the conversation with @rlewis1988 I had the illusion that we wanted to encode almost all mathematical statements, and so I started to worry about theories like category theory. If we accept that there will be limitations then I think it is fine.

Sadly I had to leave Cambridge early without refining our dialectical conversation further; the counterexamples in my head turn out to be terrible so I have to weaken my position to "*probably* theoretically impossible (to mechanize all)".

**Pull request merged**
