### PR TITLE
@[fabstract ...] user attribute

### PR DESCRIPTION
**Pull request by kodyvajjha**
Added a user attribute which also takes in an arbitrary number of [MSC 2010 classification](https://mathscinet.ams.org/msc/pdfs/classifications2010.pdf) codes as parameters.

### CODE REVIEW

**Comment by fpvandoorn** [comment]
shall I squash all commits into a single one?

**Comment by kodyvajjha** [comment]
Yes please. If you could teach me how to do it myself, I'll save you the bother from next time.

**Comment by fpvandoorn** [comment]
Ah, I forgot about this. Since we discussed some changes to it yesterday, shall I close it without merging?

**Comment by kodyvajjha** [comment]
Yes, go ahead.

I still feel having a custom user attribute could help, but I'll experiment a little before making a fresh PR.

**Pull request closed without merging**
