### PR TITLE
Use .md extension for markdown, fix typo

### PR DESCRIPTION
**Pull request by digama0**
The `.md` extension seems to be the standard for markdown files (certainly on GitHub), so we can use it instead of the longer `.markdown` extension.

@andrejbauer: You expressed disagreement with this change - why?

### CODE REVIEW

**Comment by andrejbauer** [comment]
I was told by @matijapretnar that `.markdown` is better and I just believed him. But searching around a bit reveals:

* http://hiltmon.com/blog/2012/03/07/the-markdown-file-extension/
* https://superuser.com/questions/249436/file-extension-for-markdown-files

GitHub supports both. I rather like the idea that we do not live in a 8.3 world anymore.

**Comment by andrejbauer** [comment]
Given the inessential nature of this PR, I am tempted to reject it. There are no good reasons for or against it, but there's reason not to keep changing things, and leave them as they are.

**Comment by digama0** [comment]
I'm happy with whatever people decide, but I would like to see at least one
other person weigh in first.

**Comment by fpvandoorn** [comment]
I'm used to see the `.md` instead of `.markdown` extension on GitHub, but I couldn't really care less.

**Comment by picrin** [comment]
I'm also more used to seeing .md more than .markdown, but don't care that much either.

**Pull request merged**
