### PR TITLE
Clarify the policy on how pull requests are accepted.

### PR DESCRIPTION
**Pull request by andrejbauer**
This bit of instructions explains the pull request policy. I propose that we use `n = 1` in the **`n` pairs of eyes** policy. That means, in particular (and in attention to @thalesant who just arrived) that **nobody does any direct pushes to the repository**.  Always make a pull request and wait for someone else to accept it.

### CODE REVIEW

**Comment by robertylewis** [comment]
Merged.

**Comment by andrejbauer** [comment]
I think you're supposed to press the Merge button. What did you actually do, push directly?

**Comment by andrejbauer** [comment]
Perhaps there was one commit which I added at the last moment that you missed. I don't know.

**Comment by robertylewis** [comment]
I was following the workflow used in the Lean project: I pulled your branch, rebased it on master, and pushed that directly. It avoids the useless merge commit messages. But, it takes 15 seconds, and you managed to add a commit within those 15 seconds.

**Comment by robertylewis** [comment]
Wait, maybe not? That last commit was just the merge commit.

**Comment by andrejbauer** [comment]
There was no merge commit in my PR and it was already based on `master`, wasn't it? You could just press the button.

**Comment by robertylewis** [comment]
The merge commits get added automatically when you use the button, and no, your commit was based on 463a92c.

**Comment by robertylewis** [comment]
The point may be moot. @fpvandoorn just pointed out that there's a "rebase and merge" option hidden behind the default merge button, that does exactly what I was doing manually.

**Comment by fpvandoorn** [comment]
> There was no merge commit in my PR and it was already based on master, wasn't it? You could just press the button.

I am very much in favor of the rebase approach. The history of this repository is currently already a mess with half of the commit being merge commits which do nothing and we already have a couple commits twice in the history.

I propose that when merging pull requests, we use the `rebase and merge` button (click the down arrow next to `merge pull request`). This will keep the history linear, ordered by the date it was pushed to the repository.

**Comment by favonia** [comment]
FYI: you can also "squash and merge" on GitHub now. Depending on how terrible the commit history of a PR is, this might be a better option.

**Comment by Kha** [comment]
On the settings page of a repository, there is an option to disallow merge commits (by removing the merge button). Furthermore, in the "Branches" tab branches can be protected so that they can only be changed from PRs after an approved review. While we do not use these options for Lean itself, I would suggest giving it a try for this project.

**Comment by andrejbauer** [comment]
@fpvandoorn: Ok, I'll try to remember that, I am used to just pressing big green buttons. Please don't beat me if I miss it occassionally.

@Kha: I like that idea. Let me go fiddle with the settings. Nobody should be just pushing stuff.

**Comment by andrejbauer** [comment]
I protected the branch `master` so that nobody can directly push into it, but I did not impose any other requirements on it yet (such as "must be reviewed" and "has no outstanding review points") so that we have time to learn about these things.

I disabled "merge PR" but left the others available. I hope that's the right thing to do.

**Comment by robertylewis** [comment]
That sounds ideal to me. I don't think we need to enable "must be reviewed."

**Comment by Kha** [comment]
> I protected the branch master so that nobody can directly push into it

I believe that only rejects force pushes via `git push -f`. I mostly suggested enforcing reviews as a way to stop direct pushes, but we may be able to achieve the same thing via the fabstracts organization: https://help.github.com/articles/about-branch-restrictions/

**Pull request merged**
