### PR TITLE
A finitary statement of Szemeredi’s Lemma.

### PR DESCRIPTION
**Pull request by kim-em**
(The usual infinitary version states that a subset of the natural numbers with positive upper density contains arbitrary long arithmetic sequences.)

### CODE REVIEW

**Comment by fpvandoorn** [comment]
I'm assuming that you want `r` to be positive again in `contains_arithmetic_progression_of_length'`?

**Comment by kim-em** [comment]
Thanks, fixed.

**Comment by robertylewis** [comment]
This could just be an idiosyncrasy of my combinatorics education, but I know this result as Szemeredi's Theorem; Szemeredi's (regularity) lemma is a result about graph partitions, interesting in its own right, that was used in the original proof of the theorem. Wikipedia seems to agree with me, for what it's worth. Do you have particular sources that call this result a lemma?

**Comment by robertylewis** [comment]
In general: thanks for submitting these fabstracts! This project is, obviously, in its very early stages, and we're experimenting with organization, looking for weak spots, etc. I'm particularly interested in fabstracts that push the boundaries of the "system" as it currently exists; I'm less interested in building a collection of simply-stated results right now, since that makes changing things more cumbersome. (Of course, others may feel differently.) That said, I'm more than happy to merge this one!

**Comment by spitters** [comment]
Should we encourage sharing definitions with the previous fabstract on arithmetic progressions?
I think this may greatly reduce the time to review PRs.

**Comment by andrejbauer** [comment]
I think we have plenty of fabstracts to worry about organization and should stop accepting new ones. Any change we make will likely require a reworking of existing fabstracts, or their removal. And with the removal people's feelings will be hurt. I would like to come to some sort of an agreement about foklore. Right now it's a hodgpodge of badly thought out definitions. I would like to move them all within fabstracts whence they came from, so that the bad desing isn't seeping all over the place.

**Comment by kim-em** [comment]
Hi all --- my feelings certainly won't be hurt if this or anything else is removed, rejected, etc! I'm very curious about how formalabstracts will work out, and just wanted to get started. :-)

In particular, I put this one up in large part because of its overlap with my previous fabstract of the Green-Tao theorem on arithmetic progressions in primes. I'm curious about how the process of merging overlapping mathematics will work out. @spitters above suggests that the definition of arithmetic progression should be shared with the previous fabstract --- I assume that's what you'd want to suggest in general? Should one fabstract import the other? If not, where should the common development be put?

(Responding to @rlewis1988 above, I wonder if this is already pushing the boundaries of the system...)

**Comment by kim-em** [comment]
And yes, @rlewis1988, this is indeed the Theorem, not the Lemma. (... I'd actually set out to write the fabstract for the Lemma, but decided that not enough graph theory existed in the stdlib yet to bother.) I'll fix this now.

**Comment by robertylewis** [comment]
The build is failing now: line 28 needs to be changed from "lemma" to "theorem." Also, re: @fpvandoorn's comment, do you want `r >= 1` instead of `r > 1`?

> Should one fabstract import the other? If not, where should the common development be put?

Indeed, I think this is the interesting and relevant question here. I'm growing more comfortable with the idea of one giant library ("everything in folklore" instead of "no folklore, everything in a separate fabstract"). It seems wrong for a statement of Szemeredi's lemma to depend on a statement of the Green-Tao theorem; but without a folklore folder, and with separated fabstract folders, either one has to import the other or definitions will be constantly duplicated.

By the way, my train ride ends in an hour and then I'm on vacation for the week, so I leave it to others to merge this (or not).

**Comment by andrejbauer** [comment]
I am fine with "everything is folklore" as long as there can coexist many definitions of the same thing. I am quite sure that it is wrong to impose a single definition onto everyone. The way to accomplish this is to *not have a tree* of mathematics, but a network of mathematics. If someone wants to separate out measure theory from a fabstract, for example, they should produce a `Author_X_measure_theory` and cite it all either as `FromMyHead "Author X"` or copy definitions from actual books and give proper references.

**Comment by kim-em** [comment]
I guess a separate question is the extent to which fabstracts may have
external dependencies.

If someone one day writes a nice number theory library, it seems likely
that a fabstract that needs to talk about prime numbers might want to use
it. Perhaps it's far too early to decide this yet, but what do people think
about this prospect?

As an example today, most of the definitions in
https://github.com/formalabstracts/formalabstracts/blob/master/fabstract/Bauer_A_InjBaireNat/categories.lean
are
in my category theory library <
https://github.com/semorrison/lean-category-theory>! If fabstracts is to
grow, I think we will have to think about this issue sooner rather than
later.

**Pull request closed without merging**
