### PR TITLE
Introduce "unfinished", abolish folklore

### PR DESCRIPTION
**Pull request by andrejbauer**
This rather hefty PR does the following:

1. It abolishes `folklore`. Until we have some idea what is going on, we should not try to create a
    monolithic structure called "folklore".  Mathematicians *think* that all the math out there fits
    nicely together, but we do not *actually* know how much extra work it would take to make sure
    that everything fits together *formally*. Therefore, we should *not* try to synch all the fabstracts
    through the use of `folklore`, and instead separate concerns:

      1. Write fabstracts independently of each other.
      2. Someone needs to work on how to fit them together.

   Whoever works on the second point can re-introduce folklore once it is clear what that is supposed
   to be.
2. It simplifies the `undefined_const` and `unproved_theorem` to just a single
   `unfinished` concept, as there is no need to ahve two of these. Who is going
   to remember that constants are "undefined" but theorems are "unproved"? Also,
   the simplification gets rid of some code duplication.
3. Import `meta_data` from an absolute place. Typing `...meta_data` just because
   users did not initialize the project is silly. (And we should rename `meta_data`
   to something more general.)

### CODE REVIEW

**Comment by digama0** [comment]
I notice that you reformatted my code. Although I'm fine with most of it. I want to mention that the standard lean style has no additional indent immediately after a `def`, or after the cases in a `def` or `inductive`. [Source](https://github.com/leanprover/lean2/blob/master/doc/lean/library_style.org)

**Comment by andrejbauer** [comment]
I hope I got it right.

**Comment by digama0** [comment]
Much better.

I don't think I agree with this handling of `folklore`. Besides the reasons brought up by Floris, I think that it is better to approach a math library from the assumption that there *is* only one definition until this assumption is strained or questioned by incompatible developments, rather than starting from the assumption that all math is isolated unless something explicitly causes theories to merge. There is no additional burden of fitting a paper to a pre-chosen formalization, indeed usually it is much *easier* to formalize in the presence of an existing library to graft your work onto.

In the rare cases where two diverging formalizations of the same topic become salient or necessary somehow, we can always just locally split the development or make one private to a paper, but I think in the majority of cases, the same subject in different papers will fit together well enough that we can treat it as one concept. The question of whether to organize it all in one `folklore` folder or have some other organization can be debated, but I think the general idea of merging common theories is sound.

**Comment by andrejbauer** [comment]
If we are quite honest, the unicity of mathematics is an illusion at a formal level. *Informally* it is the case that "it all fits together" and that "all mathematicians use the same definitions", but quite obviously, this will not be true at a formal level, at least not all the time. I am abolishing folklore because we are going to hit *very quickly* questions of curation of folklore, and I think it's better to avoid that.

Let us do things in steps. At this point we should *not* try to provide a monolithic, all-encomapssing, library of "agreed upon" mathematical definitions. Once we see how things are working, we may try (but I have my doubts about that).

**Comment by digama0** [comment]
I'm still not seeing it. Here is how I see it working:

* User A writes abstract `fabstracts/A` which uses theory `T`, which they think is "in the literature", so they write their formalization `TA` and add it to `folklore/TA`.
* User B finds that theory `T` is also useful in their formalization of `fabstracts/B`, and uses it. Now both `fabstracts/A` and `fabstracts/B` depend on `TA`, and the illusion that `TA` is the unique encoding of `T` is preserved.

Now in fact if user A had not formalized `TA` first, no doubt user B would have done it differently, to create `TB` instead (which is probably similar to `TA`, but is almost certainly not formally equivalent.) But the formalization `TB` is entirely counterfactual, no man-hours were spent on it.

I don't think of `folklore` as a monolithic library at all, but rather a grab bag of useful tidbits that are not local to a paper. The lean standard library is coming along, and it will be more curated and monolithic, but `folklore` will not be nearly so well-planned, since it is written by different people at different times for different purposes. It is mainly there as an aid so that people can point to an existing development if one exists rather than wasting time on foundational stuff unrelated to the paper at hand. We can continue the story:

* User C finds that `T` will be useful in their development, and finds `folklore/TA`, but decides that this formalization is inappropriate for the material at hand. So they write `folklore/TC`, and the community may debate the differences and attempt to merge them or find a common root, if anyone cares to do so. If not, then we get two versions of `T` in `folklore`.

**Comment by andrejbauer** [comment]
Can we please do things in steps? Let's have at least two fabstracts with overlapping definitions, and then we'll talk about folklore.

**Comment by andrejbauer** [comment]
You see, if we keep the folklore now, we'll want to re-organize it later. And when we do, we'll have to fix all references to it *immediately* or things will be broken.

If we abolish folklore now, then when we re-introduce it, everything will still work, and we may *gradually* improve fabstracts that do not refer to the folklore.

It's bad enough that whenever I change anything in `meta_data` I have to fix four abstracts. I don't want to experience the same pain when folklore starts changing.

Also, I am convinced that there is much less agreement between mathematicians on how precisely things are to be defined than you seem to be implying. For instance, there won't be much agreement on what the integers are (free unital ring, free group on one generator, free ring over the semigroup of natural numbers)?

**Comment by digama0** [comment]
Okay, I agree, at this point it doesn't matter how we organize those files. But in the long term it will make generic developments less discoverable, so this abolition's days are numbered.

**Comment by andrejbauer** [comment]
If you can think about how to organize `folklore`, I'd be interested to hear. Please keep in mind that mathematicians **will not** agree on important definitions, such as "real number" and "Turing machine".

**Comment by robertylewis** [comment]
I think there are a few models for this project: one provides a substantial background library for fabstract authors to build on, and another depends on the authors to provide their own background (or use background from other fabstracts). Tom said in conversation today that he has had the former model in mind. I won't try to put words in his mouth, hopefully he'll chime in here soon.

Regardless, he pointed out (and I agree) that "folklore" is the wrong name for this. It's background knowledge, or a shared library. "Folklore" implies information that is commonly known but not in the literature, but the definitions we expect to have here are all found in many places in the literature.

Tom also questioned the name of "undefined_const" and "unproved_theorem," since unproved_theorems are in fact proved, just not formally. "unformalized_theorem" is long but more descriptive. I'm not sure "unfinished" is the right keyword either, but for now I don't really care. I had them separated in case we wanted to assign different meta-data, which was a hypothetical.

**Comment by andrejbauer** [comment]
Yes, several people have complained about the choice of the word "folklore". I agree it's bad.

I think it is an *unverified assumption* that it is possible to formalize mathematics on top of a single monolithic background library. The evidence so far is that anyone who's tried to do that put enormous effort into building one (Isabelle AFP, MathComp, ...) but did not really get that far in comparison with the totality of mathematics, or even undergraduate mathematics. As my aikido teacher says, if it doesn't work, why do you keep repeating it? Try something else! We have a chance here to do precisely that!

**Pull request merged**
