### PR TITLE
Add nightlies-based Travis CI support

### PR DESCRIPTION
**Pull request by Kha**

### CODE REVIEW

**Comment by robertylewis** [comment]
Awesome, thanks! This points out that we need to update to the latest Lean changes....

**Comment by Kha** [comment]
By the way, Travis can be configured to do a daily run even if there was no commit, so that breaks due to changes in Lean are detected as well.

**Comment by favonia** [comment]
@Kha Indeed, but I guess we do not need that, because we will soon stabilize on 3.3. By the way thanks for showing `language: generic`; I did not know this undocumented feature...

**Comment by favonia** [comment]
@Kha Ah, I forgot the Lean library change, but I guess we have enough people in the Lean team to manually take care of the changes.

**Comment by favonia** [comment]
(To be clear, I am not against of daily checking, and actually wanted to enable this by myself.)

**Pull request merged**
