### PR TITLE
Fix the developer list in README.md.

### PR DESCRIPTION
**Pull request by favonia**

### CODE REVIEW

**Comment by andrejbauer** [comment]
It is always good to acknowledge people where acknowledgment is due. I think we should add @digama0 and @favonia. The list of developers should be probably in alphabetical order (as is common in math and computer science), but it should be made clear that @thalesant is the project leader.

**Comment by favonia** [comment]
@andrejbauer I guess it's done? @fpvandoorn Are the names sorted correctly? @digama0  I don't know which website should be your website.

**Comment by digama0** [comment]
I don't really have a website, I usually use `us.metamath.org` when people ask.

**Comment by favonia** [comment]
@digama0 Do you have a more specific URL? Actually, I'm done with this pull request and please update the document as you like it.

**Comment by fpvandoorn** [comment]
> @fpvandoorn Are the names sorted correctly?

Yes, according to Dutch conventions my name is sorted under `D`. Thanks!

**Comment by andrejbauer** [comment]
> Yes, according to Dutch conventions my name is sorted under D. Thanks!

This should be regulated by the EU commission.

**Comment by fpvandoorn** [comment]
> This should be regulated by the EU commission.

But how? In Belgium they sort names like mine under the `v`. Probably we (Netherlands and Belgium) do this just to confuse foreigners :)

**Pull request merged**
